### ISSUE TITLE
Don't generate ids with words in them

### ISSUE THREAD

**Issue by Scotsguy** [modrinth/labrinth#114]
Specifically to avoid slurs and such appearing in links (and potentially triggering zealous url filters), but removing words entirely is probably your best bet

**Comment by JeffAxe123** [comment]
This is a terrible idea. The words in the URL make it easier to find mods without seaching for them if you know the id

**Comment by Scotsguy** [comment]
IDs like `yBW8D80W` are already hard to remember, getting a word in there is rare too, this wouldn't make it significantly harder

**Comment by JeffAxe123** [comment]
The ids in the URLS are normally stuff like `chime` , or am I talking about `knossos' not 'labrinth'?

**Comment by Prospector** [comment]
Those are the slugs, not the ids. The ids are random characters
