### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by HeyItsJono** [modrinth/labrinth#128]
Heya, I'm unsure if this is appropriate so please go ahead and close this issue if not; but it'd be super handy if we could 'favourite' or 'star' mods in Modrinth, preferably with the ability to sort them into categories for later review!

**Comment by Geometrically** [comment]
Transferring from #129, 
"The purpose of following would be so you could see a list of updates to mods you follow that you haven't already marked as seen."
Favorites/Follows seem to functionally the same to me.
