### ISSUE TITLE
Sorting mods alphabetically

### ISSUE THREAD

**Issue by gbl** [modrinth/labrinth#130]
There should be an option to sort mods/search results alphabetically. Example: https://modrinth.com/mods?q=Giselb lists all my mods, but as there are so many of them, it's still hard to find the one you're interested in. Sorting by name would make this easier.

**Comment by haykam821** [comment]
This issue was fixed by #190.

**Comment by wafflecoffee** [comment]
> This issue was fixed by #190.

It's not actually implemented in the FE yet

**Comment by wafflecoffee** [comment]
This is not possible due to limitations in MeiliSearch. Thanks for the issue nonetheless!
