### ISSUE TITLE
Drafting Issue

### ISSUE THREAD

**Issue by SUPERN00Bthefirst** [modrinth/labrinth#141]
Unable to save mod as draft.
Upon pressing save draft button the following error is displayed:
"Database Error: Error while interacting with the database"

**Comment by Geometrically** [comment]
Have you filled out all required fields?

**Comment by SUPERN00Bthefirst** [comment]
Yes, and some of the optional.

**Comment by Geometrically** [comment]
Could you send a screenshot of the mod creation page?

**Comment by SUPERN00Bthefirst** [comment]
![image](https://user-images.githubusercontent.com/49575478/105530853-67310080-5cb6-11eb-9020-22b3ed666e36.png)

**Comment by Geometrically** [comment]
The vanity URL is required
