### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Geometrically** [modrinth/labrinth#146]
**Is your feature request related to a problem? Please describe.**
Currently, dependencies are not able to specified within the API. This poses a problem for users who need to know the dependencies of a mod in a consistent way.

**Describe the solution you'd like**
A way to specify dependencies, incompatibilities, etc within the API.

**Comment by Jefaxe** [comment]
Well its in the API, not unused. No mod has any dependcies (that i can see), and the frontend does not have a "depends" tab.
