### ISSUE TITLE
Cannot get a specific version of a a mod

### ISSUE THREAD

**Issue by Ladvace** [modrinth/labrinth#147]
**Describe the bug**

I'm calling 

`https://api.modrinth.com/api/v1/version/${MOD_VERSION_ID}`

  but I get error 404, it used to work but Idk why it's not working anymore.

**Comment by Geometrically** [comment]
What version ID are you using? Works fine for me

**Comment by Ladvace** [comment]
I tried a random one, like `YuZK7F05` from **LambDynamicLights**

**Comment by diabolical17** [comment]
I did a few tests, seems the database failed: 

![https://iili.io/fBqwEF.png](https://iili.io/fBqwEF.png)

**Comment by Ladvace** [comment]
yeah, I first got that error 502, and now I just get 404

**Comment by Geometrically** [comment]
Yep, thanks for reporting. A current workaround would be using /api/v1/versions?ids=[<id here>] route
