### ISSUE TITLE
Client Side Only / Server Side Only Catoragries

### ISSUE THREAD

**Issue by JeffAxe123** [modrinth/labrinth#158]
**Is your feature request related to a problem? Please describe.**
I would like to be able to filter by client side only (or server-side only)

**Describe the solution you'd like**
Adding client only/ server only catagories.

**Comment by Madis0** [comment]
https://github.com/modrinth/knossos/issues/100

**Comment by JeffAxe123** [comment]
Is issues for the website in knosseos or labrinth then?

**Comment by Madis0** [comment]
> Is issues for the website in knosseos or labrinth then?

Labrinth is for things that work in the background like database, virus checks, file hosting...
Knosseos are the things users can see, like search, page designs, ...
