### ISSUE TITLE
Bulk get routes only accept IDs, not usernames/slugs/etc.

### ISSUE THREAD

**Issue by ariesclark** [modrinth/labrinth#185]
https://api.modrinth.com/v2/users?ids=[%22triphora%22]
doesn't work, is there a way to fetch an array of users by their username?

**Comment by triphora** [comment]
This was added for projects a little while ago https://api.modrinth.com/v2/projects?ids=%5B%22sodium%22%5D

**Comment by ariesclark** [comment]
> This was added for projects a little while ago https://api.modrinth.com/v2/projects?ids=%5B%22sodium%22%5D

Cool, safely assuming I can close this issue then!

**Comment by triphora** [comment]
Still not implemented for usernames!

**Comment by Geometrically** [comment]
fixed with latest auth pr :)
