### ISSUE TITLE
Downloads in the API can appear to have spaces.

### ISSUE THREAD

**Issue by Jefaxe** [modrinth/labrinth#186]
**Describe the bug**
Filenames can have spaces in them on rare occasions, leading to any program accesing the API to crash. The real download also states a space, but ofcourse %20 is there in reality.

**To Reproduce**
1. Go to 'api.modrinth.com/api/v1/mod/r7aBIx6Q/version'
2. Scroll down to files > 0  (index list) > (url of filename)
3. See that the filename is LandOfSignals-1.16.4-forge-0.0.3 (1).jar

**Expected behavior**
No space, i assume it would use _ or - instead.

**Additional context**
I think this is a problem of a duplicate upload.

**Comment by Redblueflame** [comment]
This seems to be an issue from the uploader of the file. If the file contains paces, we also include it in the download link, and won't rename the file if I recall correctly.

**Comment by Jefaxe** [comment]
Yeah, but maybe there could be a special case for spaces? Like adding "-" in instead, or something like that? Otherwise all future launchers will have to manually replace " " with  "%20" and it could just be done on the backend.

**Comment by wafflecoffee** [comment]
This has been fixed with any jars that are new after the release of [v2.0.0](https://github.com/modrinth/labrinth/releases/tag/v2.0.0). That said, this still persists for anything uploaded prior to that, but I'm not sure there's an easy way to fix that.

**Comment by wafflecoffee** [comment]
These aforementioned files from before v2 were manually fixed!
