### ISSUE TITLE
Make delete featured versions button

### ISSUE THREAD

**Issue by lmg4497** [modrinth/labrinth#206]
I can't delete featured versions

**Comment by Geometrically** [comment]
Is there an error when you try deleting a featured version? Or is there no button?

**Comment by lmg4497** [comment]
No button

**Comment by Geometrically** [comment]
I'm going to close this since it is something on the frontend, and won't happen. In order to delete a featured version, you can go to the versions individual page and click the "Delete Version" button in the top left of the page.
