### ISSUE TITLE
License/Source Availability Information API for mods

### ISSUE THREAD

**Issue by sdaugherty** [modrinth/labrinth#21]
Should have license/source availability metadata that allows people to search for mods by what they are allowed to do with them:

- [ ] May be included in modpacks?
- [ ] Source available?
- [ ] Right to distribute?
- [ ] Right to modify?
- [ ] Is mod covered by multiple licenses (for example, the source code is unencumbered but the assets might be ARR?)
- [ ] License name

**Comment by Geometrically** [comment]
Filtering by license sounds cool. However it will only be for mods on our platform since those are not visible on CurseForge's API

**Comment by Aeledfyr** [comment]
We could potentially find the license from the linked sources for some mods, but that may not be 100% accurate.
