### ISSUE TITLE
Create an API route for generating stylish badges

### ISSUE THREAD

**Issue by axelrindle** [modrinth/labrinth#218]
**Is your feature request related to a problem? Please describe.**
Projects like [Shields.io](https://shields.io/) or [way2muchnoise/CurseForgeBadge](https://github.com/way2muchnoise/CurseForgeBadge) allow generating stylish badges to provide some information overview for a project. Such badges are widely seen across Github at the top of README files.

**Describe the solution you'd like**
The most easy way to accomplish badge generation would be a native implementation into the Modrinth platform or respectively the Labrinth project.

Another option would be the implementation of a much simpler route which just returns the latest version or a list of supported Minecraft Versions and/or Modloaders.

An implementation could generate badges like the following:

![latest version](https://img.shields.io/badge/modrinth-1.16.5-5ca325)
![all version version](https://img.shields.io/badge/modrinth-1.17%20%7C%201.16.5%20%7C%201.15.2-5ca325)
![supported modloaders](https://img.shields.io/badge/modrinth-Fabric-5ca325)

**Describe alternatives you've considered**
Alternatively I could generate a static badge, but that would require an extra commit per release just for updating that badge.

[Shields.io](https://shields.io/) for example allows for dynamic badge generation using a JSON endpoint and a JSONPath query, but I did not succeed in trying to work out a solution.

**Additional context**
None.

**Comment by wafflecoffee** [comment]
Just so you know, there's a (unofficial) shields generator at https://vetustus.github.io. :)

**Comment by vetustus** [comment]
I made a small service that is needed just for this.
From the currently supported badges: versions, game side (client/server), downloads and subscribers:
https://modrinth-utils.vercel.app/
Sorry for the main page, I'll do the normal design later.
There is still support for selecting styles as in shields.io, using the logo (without a long base64 string). The only reason "against" is that the service does not work on github pages, so depending on the loads and other reasons, it may work slowly (or even fall down).
However, you can use the site suggested above, but you should understand that it generates an awfully long address (especially if you want to insert the modrinth logo) and the best option that it can offer you is downloads and subscribers.

![versions](https://modrinth-utils.vercel.app/api/badge/versions?id=AANobbMI&logo=true&style=flat-square)

**Comment by wafflecoffee** [comment]
Shields.io now has native support for download total badges: https://img.shields.io/modrinth/dt/sodium
While the shields.io offering for modrinth could definitely be expanded, this is something to create an issue for on [their repo](https://github.com/badges/shields). The fact that they added modrinth download totals shows that they're (hopefully) open to adding more. :)
