### ISSUE TITLE
Allow files for disparate Minecraft versions to share the same version number

### ISSUE THREAD

**Issue by quat1024** [modrinth/labrinth#219]
(Opening this on the backend repo since I'm pretty sure it's more relevant here than on knossos)

**Is your feature request related to a problem? Please describe.**
I'm releasing and maintaining a mod in parallel, for 1.16 and 1.17 at the same time. The mod is "version 1.0.0" on both platforms, but Modrinth requires me to specify a unique version number for each .jar, even if they're for disparate Minecraft versions.

**Describe the solution you'd like**
I'd like to be able to use the same version number across .jars for different versions of Minecraft.

**Describe alternatives you've considered**
In the meantime I've been numbering them with `1.0.0.16` and `1.0.0.17`. I don't really like this; they might be mistaken for a comparable section of the version number, and it looks crappy.

**Additional context**
![image](https://user-images.githubusercontent.com/2068021/124206368-38168a80-dab1-11eb-9347-19c9d06661d3.png)

**Comment by wafflecoffee** [comment]
Fabric API uses `x.y.z+1.1x` for version names; I personally recommend using that.

**Comment by wafflecoffee** [comment]
As it stands, there are far too many things that depend on the version IDs being unique (for example, version URLs in the new frontend) that I don't think this is feasible for us to do. The best solution is as I mentioned above: use the game version identifier in the version number. This is still SemVer compliant.
