### ISSUE TITLE
RFC: Authentication 

### ISSUE THREAD

**Issue by Redblueflame** [modrinth/labrinth#24]
## Introduction
The objective of this Request For Comments is to present a possible solution to the authentication problem.
Authentication is still today an important part of every application, and if the implementation is not done right, we expose the data of users.

### Proposed solution:
The proposed solution is to use oauth2/OpenID. This is currently the specification the majority of websites follows, like Facebook, Google or Microsoft.

### Technical details

There is three ways for implementation of oauth2 in the project:

- Use a social 3rd party like one mentioned above. This is the simplest solution to implement, but forcing developers and users to use a 3rd party account to login on our platform can and will turn away users.
- Use a AaaS (Authentication as a service) 3rd party like authy. While this solution has loads of advantages in a hosted context, where we're the only one hosting the solution, but for a more broad use of the solution, this will make it harder.
- Create our own system for authentication, basing our work on frameworks like [oxyde-auth](https://github.com/HeroicKatora/oxide-auth/). This is the solution that needs the most technical explanation, and I'll be explaining that if that's the chosen solution in another RFC.

#### Client side of things
I think the part that needs the most description is the client / frontend part, as this seemed unclear.
Each client / frontend will have it's own "public key" and "private secret". While I'll call the second one private, it can be included as an environment variable at compilation time or even added in the code source (even if it's not recommended **at all!**) as these keys are just used to indicate to the server & client who's trying to connect with your account.
The keys are just used to make that appear on the screen (this is taken from discord for the example):
![Discord Oauth2 flow example](https://s3.fr-par.scw.cloud/screenshots-red/ShareX/2020/06/firefox_4KwswACAV7.png)

The part that secures the "oauth2 flow" (The dialog between the server & the client) is the `Proof Key for Code Exchange` system (I'll be calling it PKCE for simplicity). It allows the system to prevent MITM of the authorization token, returned by the browser, so a weak point of the transfer.

After all the "oauth2 flow", the client will have a JWT (Json Web Token) and is the **only way** to access the server as an authenticated client and user. The "public key" and "private secret" are only here to make sure that the application is authorized.

Then you only have to add a "Authorization: Bearer XXX", where XXX is the token you got at the last step for each call to the API.

**Comment by Geometrically** [comment]
I agree with you, we shouldn't rely on any third party and create our own system.

I have some questions though:
Where will tokens be stored?
Will tokens have to be renewed or will the user have to remove them manually?
While users of the APi will have the generate their own tokens, how will our frontend get valid tokens? Would it be decided on the current logged in account?

**Comment by cfanoulis** [comment]
token used for the frontend can be seperate from API keys (usually called session keys) and can expire after the session is over. They can be stored in a cookie, in localstorage, whatever, as long as its a JWT.

key generation should be made programnatically via the api (/api/v1/token or smth)

**Comment by Redblueflame** [comment]
I'll address theses questions now: 

@Geometrically 
**Where will tokens be stored?** In the oauth2 flow, we have two tokens to separate. If the app has asked for the "offline" scope, it will be given a "renew token", a random string of letters and numbers, that will be stored with the user in the database. The token that can be used with the API is a Signed Json Web Token, allowing for a stateless usage of the API, so no database query for users.

**Will tokens have to be renewed or will the user have to remove them manually?* As said above, the renewal will be automatic and without user interaction only with the offline scope. If you have an app that has the offline scope, you will have to remove it manually at the settings.

**While users of the APi will have the generate their own tokens, how will our frontend get valid tokens? Would it be decided on the current logged in account?** Frontends only can use the JWT, so with an attached user. For unregistered usage, you won't have to register your frontend. Also, any frontend, that we will call "client" is attached to a user or a team (teams are a little bit harder to do) to facilitate management.

@cfanoulis 
**key generation should be made programnatically via the api (/api/v1/token or smth)** I recommend against using the v1 namespace for auth, it should be located at /api/**auth**/\* to separate it more, as the v1 namespace is a "service" and the auth namespace a "provider".

**Comment by cfanoulis** [comment]
I'll assign this to myself since I've working a lot on authentication

**Comment by Geometrically** [comment]
Sounds good!

**Comment by Redblueflame** [comment]
1 think 2 ppl on this one should be mandatory, one that does, one that checks for security vulnerabilities

**Comment by sdaugherty** [comment]
I'd also recommend some form of 2FA being mandatory to submit mods / modpacks. u2f/FIDO2/webauthn support would be very nice. 

tokens should probably not be able to create other tokens - so if you are doing something that requires you to generate an API key with privileged contexts (ie write access), that needs to be restricted so that creating the key has to be done via the frontend, and requires reauthentication

**Comment by cfanoulis** [comment]
Webauthn is interesting, I'll look into it.

API keys not being able to create API keys sounds reasonable to me, but we
do need to discuss scopes (and how are we gonna store them)

**Comment by Redblueflame** [comment]
I think some kind of a special scope, like `webfront`, that is restricted to specific apps is a solution to that
