### ISSUE TITLE
RFC: Move to tokio

### ISSUE THREAD

**Issue by Geometrically** [modrinth/labrinth#25]
Currently, the project uses the async lib futures over tokio. While futures does the job, tokio has a lot more features and would make stuff a lot easier, such as:

- Easy scheduled tasks that do not block the code
- Better integration and support from current libraries
- A lot more features included by default

While futures is more used by a slight margin, I think the team could benefit from this transition.

**Comment by Redblueflame** [comment]
That's a great idea, I'll make it easier to develop for

**Comment by Aeledfyr** [comment]
How well does this interact with `actix-web`?  Actix has its own runtime, `actix-rt`, that may make using `tokio` more difficult, unless we figure out how to use both runtimes at the same time.

**Comment by Geometrically** [comment]
I'll look into this once I finish up mod creation. I believe actix has direct support for tokio.

**Comment by Geometrically** [comment]
Closing this for now as futures does what we need, and some libs we use don't support it.
