### ISSUE TITLE
Sortable 'Followed' mods

### ISSUE THREAD

**Issue by MeeniMc** [modrinth/labrinth#254]
**Is your feature request related to a problem? Please describe.**

The 'Followed' mods list is non-sortable. One really important use case is to follow what mods got updated, so at least I'd like to be able to sort them by last update date.

**Describe the solution you'd like**

Use the same filter box as the main interface, where one can select 'sort by ...' in a drop box.

**Alternative**

Followed mods are sorted by 'recently updated' by default.

**Comment by Eiion** [comment]
Might I add: An option to sort by alphabetical order.

**Comment by MeeniMc** [comment]
related to Knossos https://github.com/modrinth/knossos/issues/641#issue-1360819290

**Comment by triphora** [comment]
Merging this issue into modrinth/.github#28

**Comment by Eiion** [comment]
Closed as "not planned"? Making the followed page sortable is not planned, seriossly?
You mean closed because duplicate, don't you? Just assuming since modrinth/.github#28 is still open and the follows page currently is a completely random list that's hardly usable.

**Comment by triphora** [comment]
![image](https://user-images.githubusercontent.com/60205699/211705975-36d3e365-ab46-444b-a5a4-9911d42d4a7b.png)
"Duplicate" falls under not planned.

**Comment by Eiion** [comment]
Good to know. Thanks for sharing that.
