### ISSUE TITLE
Rudimentary Revenue System

### ISSUE THREAD

**Issue by enderger** [modrinth/labrinth#255]
**Is your feature request related to a problem? Please describe.**
As you are probably aware, CurseForge will soon be blocking third-party launchers from properly functioning. Seeing as the community is pretty riled up, an intermediary revenue system (not the promised one, but something) might be wise to attract modders to Modrinth rather than deal with CF’s crap.

**Describe the solution you'd like**
Some form of revenue system should be added to make Modrinth more appealing to the enraged community looking for alternatives.

**Describe alternatives you've considered**
An implementation of the full system is obviously not currently possible, but having something would tremendously help this platform grow when all is said and done.

**Additional context**
https://curseforge-ideas.overwolf.com/ideas/CF-I-2182

**Comment by wafflecoffee** [comment]
While planned, this is definitely a longer-term thing - there are other things we would rather get out first, such as modpacks, better authentication system, and analytics. We should probably put something out (such as a blog post) requesting contributors in specific areas so that we can get things like this out. Keep in mind that, on the feature development side, Modrinth is largely a one-person show right now.

**Comment by enderger** [comment]
I do know a bit of Rust, but not much in webdev. However, with the community in it’s current state it might be possible to recruit some others to help out.

**Comment by emielderckx** [comment]
Yes maybe some more time should be spend on enlarging the team 👍. Looks like the most important thing now

**Comment by enderger** [comment]
Perhaps adding an RFC system and some issues marked “help wanted” could be a good start to scaling. I’d love to contribute, but don’t exactly know what to extend.

**Comment by kreezxil** [comment]
Can we run our own ads on our pages such as our partner ads?

**Comment by falseresync** [comment]
As long as the parter banner doesn't violate rules, we're ok with it

**Comment by triphora** [comment]
Implemented
