### ISSUE TITLE
Projects appear on user's profiles before they have accepted the invite to contribute to that project

### ISSUE THREAD

**Issue by Sollace** [modrinth/labrinth#266]
**Describe the bug**
When you invite a member onto a project, Mordinth shows the project on their profile even before they've accepted the invite.

**To Reproduce**
1. Go to Modrinth
2. Click on "Dashboard"
3. Click on any project
4. Click on "Settings"
5. Try to invite a user to be a member of your project
6. Go to that user's profile
7. The project you have invited them to will appear as one of their projects, even though they haven't yet accepted the invite.

**Expected behavior**
The project should not appear on the other user's profile until after they have accepted the invite.

**Additional context**
I AM  AHORSE

**Comment by wafflecoffee** [comment]
duplicate #193

**Comment by Sollace** [comment]
> duplicate #193

That issue appears to relate to the API. This one is front-facing to the user

**Comment by wafflecoffee** [comment]
They have the same exact root cause. The frontend is simply an easier way to interact with the API.

**Comment by wafflecoffee** [comment]
I think this has been fixed for a while, but if not, feel free to reopen
