### ISSUE TITLE
Modrinth database is offline for several hours per night, breaking project viewing and stopping new logins

### ISSUE THREAD

**Issue by James103** [modrinth/labrinth#294]
**Describe the bug**
As of this morning (GMT-6), when I try to access any Modrinth projects, the request fails with HTTP 500, making it look like to the clients that Modrinth doesn't have any projects actually accessible for its users.

**To Reproduce**
1. Go to modrinth.com
2. Click on "Mods"
3. Click on any of the search results to go to the mod's project page.
4. Notice that the request stalls for around a minute, then times out and returns HTTP 500.
5. Notice that the client displays that failure as if the request had instead returned HTTP 404.

Alternatively,
1. GET https://api.modrinth.com/api/v1/mod/sodium
2. My response: `{"error":"database_error","description":"Database Error: pool timed out while waiting for an open connection"}`

**Expected behavior**
The data for the requested project should be returned and displayed as is without being blocked by HTTP 500.

**Comment by James103** [comment]
This was closed as resolved, but I'm getting the same error again as of 4:00 AM CST:
`{"error":"database_error","description":"Database Error: pool timed out while waiting for an open connection"}`
In addition, this error takes precedence over HTTP 404.

**Comment by Giggitybyte** [comment]
I am also having this issue.

**Comment by James103** [comment]
For similar reasons, one can't simply login to Modrinth via GitHub between midnight and sunrise. 

When clicking on "Sign in with GitHub":
1. GET https://api.modrinth.com/api/v1/auth/init?url=https://modrinth.com/
2. My response: `{"error":"database_error","description":"An unknown database error occured: pool timed out while waiting for an open connection"}`

**Comment by wafflecoffee** [comment]
Modrinth is currently the victim of some unfortunate attacks relating to download spamming, bringing down the servers when no one is available to fix them. Please be patient with us over the next few days while we work to resolve this.
