### ISSUE TITLE
Add more loaders

### ISSUE THREAD

**Issue by ThexXTURBOXx** [modrinth/labrinth#296]
**Is your feature request related to a problem? Please describe.**
I am sharing mods that can run on ModLoaderMP (yes, this thing from literally 2011/2012) or even Vanilla Minecraft as a jar-mod via Modrinth. However, these loaders (or Vanilla) are not selectable. 

**Describe the solution you'd like**
More selectable loaders would not only be nice for legacy modders. A small list of loaders that immediately come to my mind are:
 - [x] ModLoader
 - [ ] ModLoaderMP (yes, this one is different from ModLoader)
 - [x] Rift
 - [ ] Meddle
 - [x] LiteLoader
 - [ ] Java Agent
 - [ ] Base Edit (Jar Mod)
 - [ ] MCPC+ (aka Forge with Bukkit mappings)

**Describe alternatives you've considered**
Leaving the Loader field empty yields an error.

**Comment by Asbestosstar** [comment]
I would like to see LitLaunch and all other mod loaders also

**Comment by leocth** [comment]
fune

In a more serious note, supporting them would need to add logic to identify and validate the jars, which potentially could be quite an undertaking

**Comment by ThexXTURBOXx** [comment]
> What's the point on supporting incredibly old mod loaders

There is a rather large stream of people that are dedicated to legacy modding.
Popular examples include, but are not limited to ModificationStation, MCArchive, OmniArchive etc.
There is still demand for these :)

> In a more serious note, supporting them would need to add logic to identify and validate the jars, which potentially could be quite an undertaking

I am not quite sure if there is any logic to verify the jars as of right now. I was able to upload all of my mods without a problem, even though none of the labels is completely correct.
This makes me believe that either the logic is broken or not yet implemented.
And even if there is logix to verify the jars: Verifying a ModLoader/ModLoaderMP mod would basically require the same procedure as verifying a Forge mod (Forge was built on top of ModLoaderMP back in the days).
Thus, again, even if there was logic to verify these mods, the same logic must - at any point - be also able to verify Forge mods.
Also, why are we then able to select versions like `rd-132211` in the first place? Forge does only exist from `b1.7.3` onwards and Fabric only supports `b1.7.3` by using the Cursed Fabric project.
If there is no other mod loader that can be selected, it makes no sense to even give the possibility of selecting such a version.

I hope, this clears up my view on this topic :)
(After reading this again, I noticed that this text sounds a bit rude, but I have no intentions of being rude here, I am just pointing out why the current system does not make sense)

**Comment by kreezxil** [comment]
isn't it up to the launcher to know what to do with modloader field in the api response packet/json files? forgive me if I'm making scrambled eggs here.

I say just go ahead and add those, but surely don't feel obligated to implement them into your launcher. Let some other crazy launcher such as GDLauncher do it. Which btw that launcher can even launch 1.2.5 packs and yes, someone just updated a mod down there last December. not me tho.

**Comment by ThexXTURBOXx** [comment]
@kreezxil If I think about it, that's another very good point. If a launcher offers mod downloads directly from Modrinth, mods using LiteLoader or other mod loaders won't work regardless.
By adding more mod loaders to choose from, you are even **helping** these custom launchers deciding on whether the mod is supported.

**Comment by kreezxil** [comment]
@ThexXTURBOXx :)

**Comment by wafflecoffee** [comment]
ModLoader and Rift have been added.
We'll be working on adding more soon, which on the frontend would be under a "More" or "Other" header or something similar, so the large and popular loaders are more easily accessible.
![](https://cdn.discordapp.com/attachments/734077874708938867/977406886443892766/unknown.png)
![](https://cdn.discordapp.com/attachments/734077874708938867/977407042560090142/unknown.png)

**Comment by ThexXTURBOXx** [comment]
@wafflecoffee Thank you very much :D
Already enabled ModLoader for all my mods that support it and it worked flawlessly!

**Comment by unascribed** [comment]
It'd also be nice to have Java agent support, as that's effectively a mod loader built-in to Java. I of course have my own NilLoader that's based on them, but I'm far from the only person that has used it; CreeperHost recently has released some fix mods that are Java agents on CurseForge ([Log4jPatcher](https://www.curseforge.com/minecraft/mc-mods/log4jpatcher) and [TimeoutAgent](https://www.curseforge.com/minecraft/mc-mods/timeoutagent)), and some very old mods are also agents. [QuiltGoSlightlyFasterLol](https://modrinth.com/mod/quiltgoslighlyfasterlol), a mod on Modrinth already, is also a Java agent with a Quilt-based injector.

The format can be verified by checking for Agent-Class and/or Premain-Class in the META-INF/MANIFEST.MF of a jar file.

**Comment by triphora** [comment]
@ThexXTURBOXx Could you create posts for the remaining ones in modrinth/.github#106? No pressure to do this immediately, but it'd be easier to keep track of them individually there.

**Comment by ThexXTURBOXx** [comment]
@triphora Of course! Will do so within the next few days. Thanks for letting me know about that

**Comment by ThexXTURBOXx** [comment]
Done for all of them except for Java Agent.
@Prospector Maybe you can do that one as I think it's your addition, right?

**Comment by triphora** [comment]
Added that to the megathread - closing as such!

**Comment by ThexXTURBOXx** [comment]
@Prospector: Since my loader request was hidden I could not reply to it anymore on the megathread:

Actually, the inner workings of MLMP rather use ModLoader as a library, but there is little point in discussing about that. I would call MLMP rather an extension of ModLoader which is the reason the distinction between just ModLoader and MLMP was so important to me and every other legacy modder: You can load ModLoader mods in MLMP, but not vice versa.

Also, more versions are also archived here if you want to extend your archive (there are also more versions of ModLoader available etc.): https://mcarchive.net/mods/modloadermp?gvsn=

**Comment by Prospector** [comment]
It's not a loader though, it's a library that many mods depend on using the ModLoader mod loader. It doesn't load mods, it just adds new APIs for mods to use
