### ISSUE TITLE
Add ability to archive mod versions

### ISSUE THREAD

**Issue by Sjouwer** [modrinth/labrinth#318]
**Is your feature request related to a problem? Please describe.**
Right now it's only possible to delete a version of your mod. This however will remove it completely from the site. It would be nice if it's possible to also archive a version instead, just like you can archive the mod itself. This way the version would not show up in the versions list but still be available through a direct link, which would be helpful for mod packs that rely on that version. 

**Describe the solution you'd like**
Add along sides the ability to delete a version also the ability to archive it.

**Comment by Madis0** [comment]
If implementing CF-like system would be too complex/too much work, it could also just work like unlisted projects do, but instead if unlisting the entire project you just unlist one version.
