### ISSUE TITLE
Remove conversion of project dependencies to version dependencies

### ISSUE THREAD

**Issue by wafflecoffee** [modrinth/labrinth#336]
![img](https://cdn.discordapp.com/attachments/783153806531100673/966121186553638952/unknown.png)

This system has been rather buggy and doesn't really seem like the intended behaviour anyway when you set it on a project. It should be up to the applications using this data to determine the appropriate version to resolve.

**Comment by Geometrically** [comment]
I do not believe this should be removed- I think it's a useful feature. I will fix this bug though and close the issue.
