### ISSUE TITLE
Add support for server-side plugins

### ISSUE THREAD

**Issue by RedstoneWizard08** [modrinth/labrinth#339]
**Is your feature request related to a problem? Please describe.**

I would like Modrinth to allow people to publish Bukkit/Spigot server plugins on Modrinth, just as CurseForge does.

**Describe the solution you'd like**

Add "Bukkit", "Spigot", and "Paper" to the list of supported Mod Loaders.

**Describe alternatives you've considered**

None

**Additional context**

N/A

**Comment by cfpwastaken** [comment]
i like the idea, but it should go to its own tab like modpacks

**Comment by mhanuszh** [comment]
> i like the idea, but it should go to its own tab like modpacks

There should be a tab named "Plugins" next to the "Mods" tab and it could include "loaders" like bukkit, sponge and bungeecord

**Comment by RedstoneWizard08** [comment]
Server softwares that should be supported:
- Bukkit/Spigot
- Sponge
- BungeeCord
- Velocity

**Comment by mhanuszh** [comment]
@RedstoneWizard08, could you please rename this issue to represent plugins in general, and not just Bukkit forks?

**Comment by RedstoneWizard08** [comment]
> @RedstoneWizard08, could you please rename this issue to represent plugins in general, and not just Bukkit forks?

Done!

**Comment by wafflecoffee** [comment]
[honk](https://modrinth.com/plugins)
