### ISSUE TITLE
Add support for Resource Packs and Data Packs

### ISSUE THREAD

**Issue by RedstoneWizard08** [modrinth/labrinth#340]
**Is your feature request related to a problem? Please describe.**

I would like Modrinth to allow people to publish Resource Packs and Data Packs on Modrinth.

**Describe the solution you'd like**

Add "Resource Pack" and "Data Pack" to the list of supported Project Types.

**Describe alternatives you've considered**

None

**Additional context**

N/A

**Comment by ModProg** [comment]
Probably related to https://github.com/modrinth/knossos/issues/315

I would be interested to look into data packs, is there any input on what needs to be done first? Other design considerations?

**Comment by wafflecoffee** [comment]
Datapacks (as well as resource packs, shader packs, etc) would really just be adding the project type and any validators. It'd be super easy - just a matter of nobody having gotten around to it yet.

**Comment by wafflecoffee** [comment]
[honk](https://modrinth.com/resourcepacks)

Datapacks are on our roadmap alongside shaderpacks and worlds. However, we'd rather not have issues open for stuff that's on our roadmap already, since oftentimes these changes are not just backend or just frontend.
