### ISSUE TITLE
Allow Gallery Images to be Re-Ordered

### ISSUE THREAD

**Issue by Kneelawk** [modrinth/labrinth#349]
# The Issue
Currently, when a new project gallery image is added, it is added at the bottom of the list of gallery images. Some of the images I add are just silly images, but others provide actual documentation. This means that, currently, the silly images are mixed in with the documentation images and the newer, more up-to-date images are at the bottom.

# Potential Solution
It would be nice if there were some way to change the order of existing images. This could be some kind of way to drag the gallery images around to reorder them, or it could just be little arrows that allow the user to move the gallery image further up or down. Just some way to change the order would be useful.

# Possible Work-Arounds
I have considered deleting and re-uploading my gallery images in the order I need every time I want to add a new gallery image, but this is hardly an efficient solution.

**Comment by MagnusHJensen** [comment]
I'll try and work on this over the next week or two.

**Comment by Prospector** [comment]
This is actually already a thing

**Comment by triphora** [comment]
Addeed in #501

**Comment by MagnusHJensen** [comment]
Does knossos support re-ordering?

**Comment by triphora** [comment]
Yes, with the "Order Index" option when editing/creating an image

**Comment by Prospector** [comment]
It does, but not well. If you were looking to contribute something you could make them draggable to move around instead of having to manually type in the index
