### ISSUE TITLE
Exclusion Filters

### ISSUE THREAD

**Issue by Abstrusle** [modrinth/labrinth#391]
**Is your feature request related to a problem? Please describe.**
Seemingly, almost all the modpacks on Modrinth are clones of Fabulously Optimized, or kitchen sink. For users simply seeking for example, a magick-oriented modpack, sifting through kitchen sink or optimization is unnecessary. If I already own the optimization mods I like/need, I've no reason to install an optimization pack - why even show them?

**Describe the solution you'd like**
What I'm requesting is the ability to exclude certain tags from search, perhaps by a second click onto the checkbox. This would cut a tremendous amount of time when seeking a specific type of mod, or modpack.

**Additional context**
This would also better discourage tag spam, as users searching for specific content would filter away redundant tags.

**Comment by DioEgizio** [comment]
https://github.com/modrinth/knossos/issues/363

**Comment by triphora** [comment]
Already implemented on the backend, see the above linked issue for the frontend

**Comment by Minenash** [comment]
https://github.com/modrinth/knossos/issues/516 is another one to look at, since exclusions probably shouldn't be limited to a full text based search
