### ISSUE TITLE
Can't create modpacks/gliched green bar

### ISSUE THREAD

**Issue by catvin82** [modrinth/labrinth#403]
When i try to submit or save my modpack, the green progress bar goes to random places

**To Reproduce**
1. Create modpack
2. hit save as draft, or submit for review
3. See error

**Expected behavior**
For it to save the modpack

**Additional context**
Brave browser | cloudflare 1.1.1.1 WARP "proxy" enabled
![image](https://user-images.githubusercontent.com/96541972/180818214-7bb7b524-416b-4706-aa2b-55d5c3703a03.png)

**Comment by catvin82** [comment]
[Screencast from 25-07-22 10:39:38.webm](https://user-images.githubusercontent.com/96541972/180819020-6edd2f92-31ac-4fdb-a20d-a326bad8a47b.webm)

**Comment by catvin82** [comment]
https://user-images.githubusercontent.com/96541972/180820150-cb67b3ed-7442-4430-b913-af65d76c084e.mp4

**Comment by wafflecoffee** [comment]
Modpacks take a long time to upload, and this time goes up the more mods you have which aren't on Modrinth. In any event, this isn't a good place for support, please head to [our Discord](https://discord.gg/EUHuJHt) for support.
