### ISSUE TITLE
SPDX license identifiers no longer work

### ISSUE THREAD

**Issue by SoniEx2** [modrinth/labrinth#424]
**Describe the bug**

You used to be able to use SPDX license identifiers. Now it errors with something about https.

**To Reproduce**

1. `SPDX-License-Identifier: 0BSD`

**Expected behavior**

It should just work, as it used to.

**Additional context**

N/A

**Comment by wafflecoffee** [comment]
This was never really a supported use case. We found it was a security issue to allow non-HTTPS links for reasons we're not going to disclose right now. If it's desired, the SPDX link can be used instead: https://spdx.org/licenses/0BSD.html
