### ISSUE TITLE
Improve Testing

### ISSUE THREAD

**Issue by Aeledfyr** [modrinth/labrinth#45]
We need to set up more tests to make sure each part of the system functions properly.  We currently only have a few tests, so we should work on improving that.

Does `actix-web` have a good way of making a mock http request to a specific route?  Or should we just run the full server and then have a separate runner that sends requests to the specific routes?

**Comment by Geometrically** [comment]
We can look into implementing this. We shouldn't have to have the whole server running. https://actix.rs/docs/testing/ Actix seems to have a framework for this.

**Comment by triphora** [comment]
We can consider this completed as of #719, #729, #731, #754
