### ISSUE TITLE
Don't use Cloudflare

### ISSUE THREAD

**Issue by vXtreniusX** [modrinth/labrinth#456]
**Is your feature request related to a problem? Please describe.**
Using cloudflare is a bad idea, due to issues with privacy, centralization and accesibility.

See crimeflare.eu.org for more information

**Describe the solution you'd like**
Switching cloudflare to different providers, the linked repository provides alternatives (at `subfiles/alternative/cloudflare.md`)
, fastly might be an option as well.
**Describe alternatives you've considered**
Not using a cdn at all

**Additional context**

**Comment by ryanccn** [comment]
CDNs ensure fast resource access around the world, if we stop using a CDN it will slow down requests in a lot of places

**Comment by wafflecoffee** [comment]
Not feasible for us in the slightest.
