### ISSUE TITLE
Cannot create versions with a liteloader "litemod"

### ISSUE THREAD

**Issue by Sollace** [modrinth/labrinth#464]
When you select the liteloader as the mod loader and try to upload a .litemod to create a version, the save fails with the error "invalid file type for version file: litemod"

![image](https://user-images.githubusercontent.com/6429283/197204112-d4181dca-6feb-4acd-8744-f40fd2321e7b.png)

![image](https://user-images.githubusercontent.com/6429283/197204061-70edd891-c36d-47f0-880d-3a853e9cb69b.png)

**Comment by Sollace** [comment]
Relates to #296 where liteloader is one of the mod loaders with support added.

**Comment by Sollace** [comment]
Issue is still present.

![image](https://user-images.githubusercontent.com/6429283/206909051-3c4fb030-98b9-4b36-b7a1-27075eae9cad.png)

![image](https://user-images.githubusercontent.com/6429283/206908987-1561059c-e1a5-4757-9ed5-b0a587027e2f.png)

**Comment by triphora** [comment]
The changes are not yet on the production servers

**Comment by Sollace** [comment]
Will wait a bit longer then. Thanks.
