### ISSUE TITLE
Pluses in version number breaks gradle

### ISSUE THREAD

**Issue by PinkGoosik** [modrinth/labrinth#465]
**Describe the bug**
When trying to use modrinth project which has pluses in version numbers as a gradle dependency gradle goes boom

**To Reproduce**
1. Set dependency through modrinth maven in gradle project
2. Gradle can't get it

**Additional context**
Before cdn migration it wasn't an issues I think

**Comment by wafflecoffee** [comment]
Fixed by https://github.com/modrinth/sisyphus/releases/tag/v0.3.3
