### ISSUE TITLE
Email Authentication

### ISSUE THREAD

**Issue by theoparis** [modrinth/labrinth#518]
### Is your feature request related to a problem? Please describe.

As I've been trying to move my projects to gitlab due to the [missing support for ipv6 on github for years](https://github.com/orgs/community/discussions/10539#discussioncomment-4589088), I realized that modrinth doesn't seem to support a way to sign in with a email nor non-github provider.

### Describe the solution you'd like

Email based authentication

**Comment by Deftu** [comment]
This is already in the works
> + Roll out our own authentication service
(taken from the [#roadmap](https://discord.com/channels/734077874708938864/783143123651526676) channel in the [Discord](https://discord.gg/EUHuJHt) server

**Comment by triphora** [comment]
Yep, roadmap items do not need an opened issue since they always involve work in multiple repos.
