### ISSUE TITLE
Move or mirror to Codeberg.org

### ISSUE THREAD

**Issue by Sertonix** [modrinth/labrinth#544]
### Is your feature request related to a problem? Please describe.

Github does a lot of things things that are not good for the FOSS community.
For example the Github Copilot which violates licenses. A more detailed explaination can be found [here](https://sfconservancy.org/GiveUpGitHub).

### Describe the solution you'd like

[Codeberg.org](https://codeberg.org) is a very good alternative. It is completly open source and non-profit.
When moving the repos to there it would support the FOSS community.
Since Codeberg is not yet used a lot I think a mirror to github should stay.
There is also an effort to make Codeberg federative which should fix that issue in the future.

Not that moving to codeberg keeps all issues, pull requests and more!

### Describe alternatives you've considered

It would also be possible to mirror the repos to codeberg. This would allow people to contribute through it but the infrastructure would not need to change.
It would still mainly support Github though.

**Comment by Andre601** [comment]
Codeberg isn't the biggest fan of being used as a mirror for other repo hosts, so if a mirror would be made should it be `codeber -> github`

**Comment by Andre601** [comment]
> We aren't interested in exploring other alternatives at this time. GitHub has a lot of features we rely on that Codeberg doesn't have.

And those features would be...?

**Comment by triphora** [comment]
Actions, fine-grained org permissions, branch protection rules

**Comment by Andre601** [comment]
Depending on what actions are used for could they be replaced with woodpecker-ci which codeberg offers access for.

Afaik does gitea (and by extension forgejo) have branch protection.

Regarding org perms can I not say what they offer as I don't use orgs on Codeberg.

**Comment by triphora** [comment]
That was just to name a few. There are a whole bunch of things we need and our current workflow requires GitHub. If GitHub goes down in the future for whatever reason, most of the team members have local mirrors of each repo.
