### ISSUE TITLE
PerWorldPlugins returns client_side and server_side as "unknown" 

### ISSUE THREAD

**Issue by JulianVennen** [modrinth/labrinth#644]
### Describe the bug

The plugin [PerWorldPlugins](https://modrinth.com/plugin/perworldplugins) returns client side and server side compatibility as "unknown" in the API: https://api.modrinth.com/v2/project/perworldplugins

According to the API documentation, the value "unknown" should not exist. Since plugins are never supported on the client and always required on the server, it would probably it might make sense to default to these values.
There are some plugins like simple voice chat that do require a client side mod, but since these have a mod included in them, they also return the correct options.

### Steps to reproduce

1. Go to https://api.modrinth.com/v2/project/perworldplugins
2. check the value of client_side and server_side
3. Go to https://docs.modrinth.com/api-spec/#tag/project_model
4. See that these properties should only have the values "required","optional" or "unsupported"

### Expected behavior

Either the docs should contain the value "unknown" or the API should not be returning it.

**Comment by triphora** [comment]
In theory there should not be any non-draft projects that are able to return `unknown`. I've fixed PerWorldPlugins; if you come across any others, please report it using the Report feature on the site under the category "invalid metadata".

More context: https://github.com/modrinth/docs/pull/31#discussion_r835992496

**Comment by JulianVennen** [comment]
I have found 86 other projects with the same problem:

| Slug                                                                                                                                | ID       | Client   | Server   |
|-------------------------------------------------------------------------------------------------------------------------------------|----------|----------|----------|
| [hyper-realistic-sky](https://modrinth.com/project/hyper-realistic-sky)                                                             | PsMUgCo5 | unknown  | unknown  |
| [mmmmmmmmmmmm](https://modrinth.com/project/mmmmmmmmmmmm)                                                                           | Adega8YN | unknown  | unknown  |
| [minimal](https://modrinth.com/project/minimal)                                                                                     | Q3v8it82 | unknown  | unknown  |
| [eclectic-trove-legendary-tooltips](https://modrinth.com/project/eclectic-trove-legendary-tooltips)                                 | 8GunilxB | unknown  | unknown  |
| [purple-gui](https://modrinth.com/project/purple-gui)                                                                               | CghMkzlW | unknown  | unknown  |
| [fat-experience-orbs](https://modrinth.com/project/fat-experience-orbs)                                                             | dbigkc0P | unknown  | unknown  |
| [f8thful](https://modrinth.com/project/f8thful)                                                                                     | ZrW0og1b | unknown  | unknown  |
| [dark-mode-everywhere-fabric](https://modrinth.com/project/dark-mode-everywhere-fabric)                                             | bJF8eNMy | required | unknown  |
| [modern-font-pack](https://modrinth.com/project/modern-font-pack)                                                                   | 2C5ThaTB | unknown  | unknown  |
| [better-water-](https://modrinth.com/project/better-water-)                                                                         | sDf2tmD8 | unknown  | unknown  |
| [mscakes](https://modrinth.com/project/mscakes)                                                                                     | mtzLWCA5 | unknown  | unknown  |
| [poko](https://modrinth.com/project/poko)                                                                                           | MeBY1jLx | required | unknown  |
| [better-keep-inventory](https://modrinth.com/project/better-keep-inventory)                                                         | AJP9kwFS | unknown  | unknown  |
| [programmer-art-plus](https://modrinth.com/project/programmer-art-plus)                                                             | NGYridKF | unknown  | unknown  |
| [bcl](https://modrinth.com/project/bcl)                                                                                             | eotXuHjA | unknown  | unknown  |
| [embellished-stone-advancements-plaques](https://modrinth.com/project/embellished-stone-advancements-plaques)                       | wFLeBRkG | unknown  | unknown  |
| [drowns-tool-tweaks](https://modrinth.com/project/drowns-tool-tweaks)                                                               | BULmW8dH | unknown  | unknown  |
| [tightfault-revamp-edit](https://modrinth.com/project/tightfault-revamp-edit)                                                       | nfw2Qplb | unknown  | unknown  |
| [reforged-armory](https://modrinth.com/project/reforged-armory)                                                                     | dOT3fQ9Z | unknown  | unknown  |
| [lunar-client-fire-fix](https://modrinth.com/project/lunar-client-fire-fix)                                                         | TPoj4BTg | unknown  | unknown  |
| [saiko-lightsaber-pack](https://modrinth.com/project/saiko-lightsaber-pack)                                                         | P9pd23AT | unknown  | unknown  |
| [allay-totem-of-undying](https://modrinth.com/project/allay-totem-of-undying)                                                       | lrjtnlyr | unknown  | unknown  |
| [variant-barrels](https://modrinth.com/project/variant-barrels)                                                                     | E15aXf4P | unknown  | unknown  |
| [unified-zombies](https://modrinth.com/project/unified-zombies)                                                                     | LaK75rwp | unknown  | unknown  |
| [invisible-frames](https://modrinth.com/project/invisible-frames)                                                                   | K5IRddrD | unknown  | unknown  |
| [dls-creeper](https://modrinth.com/project/dls-creeper)                                                                             | aG78N9Bx | unknown  | unknown  |
| [smooth-font-pack](https://modrinth.com/project/smooth-font-pack)                                                                   | 4UpjQtW1 | unknown  | unknown  |
| [uncrafted](https://modrinth.com/project/uncrafted)                                                                                 | Ih3e7dxQ | unknown  | unknown  |
| [oreocookies](https://modrinth.com/project/oreocookies)                                                                             | rKriEfdt | unknown  | unknown  |
| [echo-bow](https://modrinth.com/project/echo-bow)                                                                                   | lLAWKT6P | unknown  | unknown  |
| [xitemsremover](https://modrinth.com/project/xitemsremover)                                                                         | rVsfsOIc | unknown  | required |
| [custom-join-messages](https://modrinth.com/project/custom-join-messages)                                                           | PJMIw5vh | unknown  | unknown  |
| [instakillmobs](https://modrinth.com/project/instakillmobs)                                                                         | 484RbWh7 | unknown  | unknown  |
| [better-map-items](https://modrinth.com/project/better-map-items)                                                                   | EYdutVcx | unknown  | unknown  |
| [gentle-picking](https://modrinth.com/project/gentle-picking)                                                                       | YVYq7eox | unknown  | unknown  |
| [blockprot](https://modrinth.com/project/blockprot)                                                                                 | uF5ePKuc | unknown  | unknown  |
| [cosmorp](https://modrinth.com/project/cosmorp)                                                                                     | ORIVoodV | unknown  | unknown  |
| [mods-ru](https://modrinth.com/project/mods-ru)                                                                                     | GsoCvyCO | unknown  | unknown  |
| [hide-chat-toasts-and-chat-bars](https://modrinth.com/project/hide-chat-toasts-and-chat-bars)                                       | yvdkGUKV | unknown  | unknown  |
| [void-opal](https://modrinth.com/project/void-opal)                                                                                 | s3w3N7Ae | unknown  | unknown  |
| [8-bit](https://modrinth.com/project/8-bit)                                                                                         | 81sDA1s6 | unknown  | unknown  |
| [future-hud-advancement-plaques](https://modrinth.com/project/future-hud-advancement-plaques)                                       | Bz67TFp7 | unknown  | unknown  |
| [rop](https://modrinth.com/project/rop)                                                                                             | 9E0mswEP | unknown  | unknown  |
| [more-amethyst-recipes](https://modrinth.com/project/more-amethyst-recipes)                                                         | DcLnY1WI | unknown  | unknown  |
| [unique-wood](https://modrinth.com/project/unique-wood)                                                                             | n2gf39xI | unknown  | unknown  |
| [better-ladder-3d](https://modrinth.com/project/better-ladder-3d)                                                                   | OcH26jny | unknown  | unknown  |
| [chromahudfabric](https://modrinth.com/project/chromahudfabric)                                                                     | PzuxEnMj | unknown  | unknown  |
| [universal-multi-stone-ores](https://modrinth.com/project/universal-multi-stone-ores)                                               | oLu8l2s0 | unknown  | unknown  |
| [hidden-totem](https://modrinth.com/project/hidden-totem)                                                                           | RHeHDY7P | unknown  | unknown  |
| [aon-dark-ui-overhual](https://modrinth.com/project/aon-dark-ui-overhual)                                                           | bDPrulz9 | unknown  | unknown  |
| [compact-font](https://modrinth.com/project/compact-font)                                                                           | JsMwJ2g4 | unknown  | unknown  |
| [yourscraft](https://modrinth.com/project/yourscraft)                                                                               | ggjO7jmL | unknown  | unknown  |
| [better-spruce-trapdoor](https://modrinth.com/project/better-spruce-trapdoor)                                                       | V4SKvoqS | unknown  | unknown  |
| [jappafied-aethers](https://modrinth.com/project/jappafied-aethers)                                                                 | NxpNOKEe | unknown  | unknown  |
| [shine-v1.0](https://modrinth.com/project/shine-v1.0)                                                                               | ECvAxsVf | unknown  | unknown  |
| [chromium-amethysts](https://modrinth.com/project/chromium-amethysts)                                                               | faoF1lBT | unknown  | unknown  |
| [dynamite-totem](https://modrinth.com/project/dynamite-totem)                                                                       | S14aIkRR | unknown  | unknown  |
| [gilded-ingot](https://modrinth.com/project/gilded-ingot)                                                                           | 2VLZ3B93 | unknown  | unknown  |
| [amazingly-optimized](https://modrinth.com/project/amazingly-optimized)                                                             | Z1LYQaOH | required | unknown  |
| [better-head-holding](https://modrinth.com/project/better-head-holding)                                                             | umGMT7Ze | unknown  | unknown  |
| [opendyslexicfont](https://modrinth.com/project/opendyslexicfont)                                                                   | cawT25HC | unknown  | unknown  |
| [chunkheat](https://modrinth.com/project/chunkheat)                                                                                 | BuVzcqkn | unknown  | unknown  |
| [better-bookshelves](https://modrinth.com/project/better-bookshelves)                                                               | rzDBk64g | unknown  | unknown  |
| [iaxpresencefootsteps](https://modrinth.com/project/iaxpresencefootsteps)                                                           | AoyJXBFB | unknown  | unknown  |
| [better-droppers-and-dispensers](https://modrinth.com/project/better-droppers-and-dispensers)                                       | C4g2D1mv | unknown  | unknown  |
| [my_village_pack](https://modrinth.com/project/my_village_pack)                                                                     | exT8xX0I | unknown  | unknown  |
| [greyscale](https://modrinth.com/project/greyscale)                                                                                 | mHNsfZ54 | unknown  | unknown  |
| [spoingly-slimes](https://modrinth.com/project/spoingly-slimes)                                                                     | QucKkIqL | unknown  | unknown  |
| [chappeau](https://modrinth.com/project/chappeau)                                                                                   | 4FLfsAEn | unknown  | unknown  |
| [ctov-domesticated-innovation-compat](https://modrinth.com/project/ctov-domesticated-innovation-compat)                             | BORRKwOq | unknown  | unknown  |
| [animeboard](https://modrinth.com/project/animeboard)                                                                               | vsxVlREP | unknown  | required |
| [simple-blue-gui](https://modrinth.com/project/simple-blue-gui)                                                                     | 3NFPhQvK | unknown  | unknown  |
| [styled-enchanting-tables](https://modrinth.com/project/styled-enchanting-tables)                                                   | q369WoPk | unknown  | unknown  |
| [purpurpacks-pickaxe-effective-light-source-blocks](https://modrinth.com/project/purpurpacks-pickaxe-effective-light-source-blocks) | ERLjKg7g | unknown  | required |
| [figurative](https://modrinth.com/project/figurative)                                                                               | KserzJKv | unknown  | unknown  |
| [pgm-sounds](https://modrinth.com/project/pgm-sounds)                                                                               | KbOhZv1T | unknown  | unknown  |
| [colored-whiteboard](https://modrinth.com/project/colored-whiteboard)                                                               | j5AyZaqe | unknown  | unknown  |
| [blueprinted](https://modrinth.com/project/blueprinted)                                                                             | GygNYJ1O | unknown  | unknown  |
| [headstones](https://modrinth.com/project/headstones)                                                                               | owmHZ0lO | unknown  | required |
| [skulltohead](https://modrinth.com/project/skulltohead)                                                                             | Mkl8Htig | unknown  | unknown  |
| [sunrise](https://modrinth.com/project/sunrise)                                                                                     | cDCyvHfr | unknown  | unknown  |
| [computercraft-pastebin-patch](https://modrinth.com/project/computercraft-pastebin-patch)                                           | 65CVhIWm | unknown  | unknown  |
| [raiguri-better-potr](https://modrinth.com/project/raiguri-better-potr)                                                             | BqIuonip | unknown  | unknown  |
| [green-screen-panorama](https://modrinth.com/project/green-screen-panorama)                                                         | QOHBbtD7 | unknown  | unknown  |
| [geeksmp](https://modrinth.com/project/geeksmp)                                                                                     | DW75m6hC | unknown  | unknown  |
| [purpurpacks-stone-to-iron-tools-upgrades](https://modrinth.com/project/purpurpacks-stone-to-iron-tools-upgrades)                   | 8zLmjJ4K | unknown  | required |

**Comment by JulianVennen** [comment]
any update on this?

**Comment by triphora** [comment]
Went in and fixed them all.
```sql
labrinth.public> SELECT t.*
                 FROM public.mods t
                 WHERE (client_side = 4 OR server_side = 4) AND status = 'approved'
                 LIMIT 501

-- From...
[2023-07-23 17:17:29] 84 rows retrieved starting from 1 in 361 ms (execution: 318 ms, fetching: 43 ms)

-- To...
[2023-07-23 17:30:53] 0 rows retrieved in 95 ms (execution: 86 ms, fetching: 9 ms)
