### ISSUE TITLE
cant login with my mc account

### ISSUE THREAD

**Issue by fakeman6288** [modrinth/labrinth#684]
### Describe the bug

Minecraft authentication Hydra error: In Bearer token flow: Response didn't contain valid bearer token. body: { "path" : "/launcher/login" }

**Comment by bionicy** [comment]
me too i cant log in

**Comment by glucenaphene** [comment]
same issue for me, same code

**Comment by triphora** [comment]
This bug should now be fixed. Please let us know on [our Discord](https://discord.gg/modrinth) if you encounter it again.
