### ISSUE TITLE
Add reviews and rates

### ISSUE THREAD

**Issue by ancap-kun** [modrinth/labrinth#689]
### Is your suggested enhancement related to a problem? Please describe.

I'm always frustrated when I can't leave review to plugin

### Describe the solution you'd like

Add reviews as on spigotmc.org

**Comment by triphora** [comment]
This is already listed on [our Roadmap](https://roadmap.modrinth.com) alongside comments (not sure if we will add comments or reviews or both). Please do not make issues for items that are already on the Roadmap.
