### ISSUE TITLE
Loader / Version search is not an intersection on versions

### ISSUE THREAD

**Issue by endigma** [modrinth/labrinth#697]
### Is your suggested enhancement related to a problem? Please describe.

![image](https://github.com/modrinth/labrinth/assets/34945114/78d363bc-a302-470b-bcae-3259d4e58604)
includes a mod with
![image](https://github.com/modrinth/labrinth/assets/34945114/0411cdda-001b-431a-bbfb-4c3d3f661b14)

Searching for "Fabric" and "1.20.1" returns mods that have fabric versions OR 1.20.1 versions, instead of the intersection of those.

### Describe the solution you'd like

I think more intuitively it should search for mods available under both filters

**Comment by triphora** [comment]
Duplicate of modrinth/knossos#447

**Comment by endigma** [comment]
That issue calls it a labrinth problem, not a knossos problem? This also occurs with the API.

**Comment by triphora** [comment]
There is not really any way for us to have cross-repository issues, so anything affecting both frontand and backend tends to be put on the frontend, since our development approach is backend-first.
