### ISSUE TITLE
NeoForge update json

### ISSUE THREAD

**Issue by UpcraftLP** [modrinth/labrinth#869]
### Is your suggested enhancement related to a problem? Please describe.

Currently, labrinth already has built-in support for `Forge` update json files (at `https://api.modrinth.com/updates/{slug|projectID}/forge_updates.json`), but not for `NeoForge`.

### Describe the solution you'd like

It would be nice to add another endpoint for NeoForge as well.

### Describe alternatives you've considered

Using the same file for both forge and neoforge, while technically *possible*, is not a good idea imho since a project might have different versions for each.

**Comment by Prospector** [comment]
Last we spoke to the NeoForge team I believe they told us we should hold off because they may change the format, but it seems like they haven't yet?

**Comment by UpcraftLP** [comment]
I see, I was not aware of that.

**Comment by triphora** [comment]
This already exists:
https://api.modrinth.com/updates/jei/forge_updates.json?neo=only
https://api.modrinth.com/updates/jei/forge_updates.json?neo=include

**Comment by UpcraftLP** [comment]
> This already exists: [api.modrinth.com/updates/jei/forge_updates.json?neoforge=only](https://api.modrinth.com/updates/jei/forge_updates.json?neoforge=only) [api.modrinth.com/updates/jei/forge_updates.json?neoforge=include](https://api.modrinth.com/updates/jei/forge_updates.json?neoforge=include)

Okay, that's missing in the API documentation then.
