### ISSUE TITLE
Mod filtering not working

### ISSUE THREAD

**Issue by rc6ty** [modrinth/labrinth#929]
### Describe the bug

When chosing to filter out certain mod versions the filters do not apply. 

Reproducable both on chrome and firefox on two separate devices.

### Steps to reproduce

- Go to any mod on the site
- Go to versions tab
- Filter the versions by game version or modloader

### Expected behavior

Filtering out mod versions that do not meet the chosen filters.

**Comment by Prospector** [comment]
Just pushed a fix, should be live in a few moments
